version: '3'

services:
    # The NGINX web/reverse-proxy server.
    nginx:
      depends_on:
        - app
      image: nginx:1.10.3-alpine
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes_from:
        - app
      volumes:
        - ./cnf/site.conf:/etc/nginx/conf.d/default.conf
        # Remove the comment below to enable nginx logs.
        #- ./logs/nginx/:/var/log/nginx/
      networks:
        - app-network
    # The Laravel app.
    app:
      depends_on:
       - db
      # Extend php:fpm-alpine to add PDO drivers
      build:
        dockerfile: Dockerfile
        context: .
      restart: always
      volumes:
        - .:/var/www/html
      links:
        - db:dbhost
      networks:
        - app-network
      env_file:
        - .env
    # The database server.
    db:
      image: mysql:5.7
      restart: always
      # Get environment variables from a file. Note: Rename mysql.env.example to add your config.
      env_file:
        - ./cnf/mysql.env
      # Change this if you want to use a location on the host, or it will use a Docker volume.
      volumes:
        - db_data:/var/lib/mysql
      networks:
        - app-network
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      env_file:
        - ./cnf/mysql.env
      environment:
        PMA_HOST: db
      networks:
        - app-network
networks:
    app-network:
      driver: bridge
volumes:
  db_data:
